export const metadata = {
  title: "Theaters - NextFlix App",
  description: "Generated by create next app",
};

export default function TheatersLayout({ children }) {
  return <main>{children}</main>;
}
