export const metadata = {
  title: "Contact - NextFlix App",
  description: "Generated by create next app",
};

export default function ContactLayout({ children }) {
  return <main>{children}</main>;
}
