export const metadata = {
  title: "Comments - NextFlix App",
  description: "Generated by create next app",
};

export default function CommentsLayout({ children }) {
  return <main>{children}</main>;
}
