import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        rel="stylesheet"
        href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
        // crossOrigin=""
        crossOrigin="anonymous"
        precedence="default"
        // fetchPriority="high"
      />
      <body className={`${inter.className} relative`}>
        <ClerkProvider
          appearance={{
            baseTheme: "",
          }}
        >
          <Navbar />
          <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            {children}
            {/* <SpeedInsights /> */}
          </main>
        </ClerkProvider>
      </body>
    </html>
  );
}
