export const metadata = {
  title: "User Profile - NextFlix App",
  description: "Generated by create next app",
};

export default function ProfileLayout({ children }) {
  return <main>{children}</main>;
}
