export const metadata = {
  title: "Movies - NextFlix App",
  description: "Generated by create next app",
};

export default function MoviesLayout({ children }) {
  return <main>{children}</main>;
}
